apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksdeploy 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdeploy
  template:
    metadata:
      labels:
        app: aksdeploy 
    spec:
      containers:
        - name: aksdeploy 
          image: aksdevopsacrdonald.azurecr.io/aksdeploy
          ports:
          - containerPort: 80